server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://eureka6001:6001/eureka, http://eureka6002:6002/eureka
  instance:
    instance-id: provider2   #在信息列表显示主机名称
    prefer-ip-address: true  # 访问路径变为ip地址

spring:
  application:
    name: provider  # 名字相同则认为是同一个服务