server:
  port: 80
eureka:
  client: # 客户端进行Eureka注册的配置
    register-with-eureka: false # 不在eureka之中进行注册
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka,http://edmin:mldnjava@eureka-7002.com:7002/eureka,http://edmin:mldnjava@eureka-7003.com:7003/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: upload.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址

