server:
  port: 80


feign:
  hystrix:
    enabled: true


eureka:
  client:
    register-with-eureka: false
    service-url:
         defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka,http://edmin:mldnjava@eureka-7002.com:7002/eureka,http://edmin:mldnjava@eureka-7003.com:7003/eureka