server:
  port: 7001

spring:
  application:
    name: consumer

eureka:
  client:
    service-url:
      defaultZone: http://eureka6001:6001/eureka, http://eureka6002:6002/eureka
    fetch-registry: true
  instance:
    instance-id: consumer   #在信息列表显示主机名称
    prefer-ip-address: true  # 访问路径变为ip地址