server:
  port: 8888
spring:
  application:
    name: zuul
zuul:
  routes:
    app:
      path: /app/*
      serviceId: article
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    prefer-ip-address: true
    instance-id: zuul.com