server:
  port: 6001

spring:
  application:
    name: eureka6001

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://47.112.142.231:6001/eureka, http://47.112.142.231:6002/eureka

