server:
  port: 7000
spring:
  application:
    name: eureka_demo
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://47.112.142.231:${server.port}/eureka