server:
  port: 9001
spring:
  application:
    name: article
  datasource:
    url: jdbc:mysql://localhost:3306/docker_test?characterEncoding=UTF8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    prefer-ip-address: true
    #instance-id: article.com  如果需要在eureka注册多个服务，不能写死instance-id